export const UNAUTHORIZED = 'UNAUTHORIZED';

export const UNAUTHENTICATED = 'UNAUTHENTICATED';

export const DOMAIN_ARGUMENT_INVALID = 'DOMAIN_ARGUMENT_INVALID';

export const GENERIC_DOMAIN_ERROR = 'GENERIC_DOMAIN_ERROR';

export const INVALID_OPERATION = 'INVALID_OPERATION';

export const NOT_DOMAIN_ERROR = 'NOT_DOMAIN_ERROR';

export const NOT_FOUND = 'NOT_FOUND';

export const ENTITY_CONFLICTED = 'ENTITY_CONFLICTED';

export const UNABLE_TO_CREATE_USER_ON_IDENTITY = 'UNABLE_TO_CREATE_USER_ON_IDENTITY';

export const USER_LOCKED_OUT = 'USER_LOCKED_OUT';

export const REQUIRES_TWO_FACTOR = 'REQUIRES_TWO_FACTOR';